# Custom Chatbot Project

I chose the character_descriptions dataset. With a context provided, I can ask the AI specific questions about characters, using their names for example, whereas without context, the AI would have no idea which characters I'm referring to.

## Data Wrangling

TODO: In the cells below, load your chosen dataset into a `pandas` dataframe with a column named `"text"`. This column should contain all of your text data, separated into at least 20 rows.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("data/character_descriptions.csv")
df.head()

    Name                                        Description Medium  Setting
0  Emily  A young woman in her early 20s, Emily is an as...   Play  England
1   Jack  A middle-aged man in his 40s, Jack is a succes...   Play  England
2  Alice  A woman in her late 30s, Alice is a warm and n...   Play  England
3    Tom  A man in his 50s, Tom is a retired soldier and...   Play  England
4  Sarah  A woman in her mid-20s, Sarah is a free-spirit...   Play  England

In [5]:
# Initialize an empty list to store the concatenated strings
concatenated_texts = []

# Loop through each row in the DataFrame
for index, row in df.iterrows():
    concatenated_text = f"{row['Name']}: {row['Description']}, {row['Medium']}, {row['Setting']}"
    concatenated_texts.append(concatenated_text)

# Create a new DataFrame with the concatenated texts
df = pd.DataFrame(concatenated_texts, columns=['text'])
df

                                                 text
0   Emily: A young woman in her early 20s, Emily i...
1   Jack: A middle-aged man in his 40s, Jack is a ...
2   Alice: A woman in her late 30s, Alice is a war...
3   Tom: A man in his 50s, Tom is a retired soldie...
4   Sarah: A woman in her mid-20s, Sarah is a free...
5   George: A man in his early 30s, George is a ch...
6   Rachel: A woman in her late 20s, Rachel is a s...
7   John: A man in his 60s, John is a retired prof...
8   Maria: A middle-aged Latina woman in her 40s, ...
9   Caleb: A young African American man in his ear...
10  Tyler: A white man in his mid-30s, Tyler is a ...
11  Sonya: A white woman in her late 20s, Sonya is...
12  Manuel: A middle-aged Hispanic man in his 50s,...
13  Will: A white man in his early 40s, Will is a ...
14  Mia: A young Australian woman in her mid-20s, ...
15  Lucas: A middle-aged Australian man in his 40s...
16  Tahlia: A young Indigenous Australian woman in...
17  Max: A white Australian man in his late 20s, M...
18  Ava: A middle-aged Australian woman in her 50s...
19  Donna: A seasoned performer with a larger-than...
20  Johnny: A young up-and-coming performer, Johnn...
21  Sable: A sultry and dramatic performer, Sable ...
22  Dolly: A bubbly and vivacious performer, Dolly...
23  Vixen: A fierce and competitive performer, Vix...
24  Karma: A chameleon-like performer, Karma is kn...
25  Crystal: A quirky and imaginative performer, C...
26  Olivia: A confident and charismatic marketing ...
27  Marcus: A charming and successful entrepreneur...
28  Maya: A kind and compassionate nurse with a he...
29  James: A handsome and athletic personal traine...
30  Sophia: A fun-loving and adventurous travel bl...
31  Noah: A quirky and creative graphic designer, ...
32  Chloe: A driven and ambitious attorney, Chloe ...
33  Jake: A laid-back and easygoing firefighter, J...
34  Prince Lorenzo: A charming and handsome prince...
35  Signora Rosa: A mysterious and alluring woman ...
36  Baron Gustavo: A wealthy and arrogant nobleman...
37  Francesca: A fiery and passionate young woman ...
38  Don Carlo: A charming and charismatic young ma...
39  Duke Orsino: A pompous and self-important nobl...
40  Lady Olivia: A wealthy and beautiful noblewoma...
41  Sir Toby Belch: A drunken and lecherous knight...
42  Malvolio: A pompous and self-righteous steward...
43  Viola: A plucky and resourceful young woman wh...
44  Sir Andrew Aguecheek: A dim-witted and gullibl...
45  Bianca: Lady Olivia's cunning and quick-witted...
46  Sebastian: Viola's twin brother, who is also s...
47  Feste: A jester and musician who works in Lady...
48  Antonio: A sea captain who rescues Sebastian f...
49  Abigail: A plucky and resourceful young woman ...
50  Thomas: A good-natured and affable young man w...
51  Reverend Brown: The pious and stern minister o...
52  Captain James: The charismatic and dashing cap...
53  Mrs. Mercer: The matriarch of the wealthiest f...
54  Mr. Mercer: The bumbling and absent-minded pat...

## Custom Query Completion

TODO: In the cells below, compose a custom query using your chosen dataset and retrieve results from an OpenAI `Completion` model. You may copy and paste any useful code from the course materials.

In [6]:
import openai
openai.api_base = "https://openai.vocareum.com/v1"
openai.api_key = # SECRET

In [7]:
# Using Code from 4.24 Case Study Workspace
# Generate and save embeddings

EMBEDDING_MODEL_NAME = "text-embedding-ada-002"
batch_size = 100
embeddings = []
for i in range(0, len(df), batch_size):
    # Send text data to OpenAI model to get embeddings
    response = openai.Embedding.create(
        input=df.iloc[i:i+batch_size]["text"].tolist(),
        engine=EMBEDDING_MODEL_NAME
    )
    
    # Add embeddings to list
    embeddings.extend([data["embedding"] for data in response["data"]])

# Add embeddings list to dataframe
df["embeddings"] = embeddings
df.to_csv("embeddings.csv")
df

,text,embeddings
0,"Emily: A young woman in her early 20s, Emily i...","[-0.016379576176404953, -0.014448083005845547,..."
1,"Jack: A middle-aged man in his 40s, Jack is a ...","[0.00714816665276885, -0.022021278738975525, 0..."
2,"Alice: A woman in her late 30s, Alice is a war...","[0.005913194734603167, -0.011871776543557644, ..."
3,"Tom: A man in his 50s, Tom is a retired soldie...","[0.017878901213407516, -0.017596535384655, 0.0..."
4,"Sarah: A woman in her mid-20s, Sarah is a free...","[-0.018298335373401642, -0.02350444905459881, ..."
5,"George: A man in his early 30s, George is a ch...","[-0.020879525691270828, -0.012621497735381126,..."
6,"Rachel: A woman in her late 20s, Rachel is a s...","[-0.0037319459952414036, -0.009705585427582264..."
7,"John: A man in his 60s, John is a retired prof...","[0.019646571949124336, -0.013807781040668488, ..."
8,"Maria: A middle-aged Latina woman in her 40s, ...","[-0.006911840755492449, -0.013061589561402798,..."
9,Caleb: A young African American man in his ear...,"[0.006823256146162748, -0.029563192278146744, ..."
10,"Tyler: A white man in his mid-30s, Tyler is a ...","[0.013335198163986206, -0.048971496522426605, ..."
11,"Sonya: A white woman in her late 20s, Sonya is...","[0.006791851948946714, -0.03281968832015991, -..."
12,"Manuel: A middle-aged Hispanic man in his 50s,...","[-0.008526013232767582, -0.022947043180465698,..."
13,"Will: A white man in his early 40s, Will is a ...","[-0.0026530236937105656, -0.046536002308130264..."
14,"Mia: A young Australian woman in her mid-20s, ...","[-0.013563292101025581, -0.022774379700422287,..."
15,Lucas: A middle-aged Australian man in his 40s...,"[0.004014276433736086, -0.0179184190928936, -0..."
16,Tahlia: A young Indigenous Australian woman in...,"[-0.01594378985464573, -0.012738263234496117, ..."
17,"Max: A white Australian man in his late 20s, M...","[0.0021642628125846386, -0.03667907789349556, ..."
18,Ava: A middle-aged Australian woman in her 50s...,"[-0.00012268566933926195, -0.00761997047811746..."
19,Donna: A seasoned performer with a larger-than...,"[-0.027097031474113464, -0.018302153795957565,..."
20,"Johnny: A young up-and-coming performer, Johnn...","[-0.03135303407907486, -0.024801846593618393, ..."
21,"Sable: A sultry and dramatic performer, Sable ...","[-0.029338078573346138, -0.018894359469413757,..."
22,"Dolly: A bubbly and vivacious performer, Dolly...","[-0.035839010030031204, -0.019233515486121178,..."
23,"Vixen: A fierce and competitive performer, Vix...","[-0.036363694816827774, -0.025237884372472763,..."
24,"Karma: A chameleon-like performer, Karma is kn...","[-0.005941613111644983, -0.018105927854776382,..."
25,"Crystal: A quirky and imaginative performer, C...","[-0.009453645907342434, -0.014112434349954128,..."
26,Olivia: A confident and charismatic marketing ...,"[-0.0073702577501535416, -0.016184642910957336..."
27,Marcus: A charming and successful entrepreneur...,"[-0.009401591494679451, -0.04195664823055267, ..."
28,Maya: A kind and compassionate nurse with a he...,"[-0.028294377028942108, -0.024649009108543396,..."
29,James: A handsome and athletic personal traine...,"[-0.02195400930941105, -0.012563727796077728, ..."
30,Sophia: A fun-loving and adventurous travel bl...,"[0.01387482974678278, -0.019231650978326797, -..."
31,"Noah: A quirky and creative graphic designer, ...","[-0.020587317645549774, -0.02017899602651596, ..."
32,"Chloe: A driven and ambitious attorney, Chloe ...","[-0.007095130626112223, -0.013222445733845234,..."
33,"Jake: A laid-back and easygoing firefighter, J...","[-0.014207241125404835, -0.021265199407935143,..."
34,Prince Lorenzo: A charming and handsome prince...,"[-0.0037086326628923416, -0.015919039025902748..."
35,Signora Rosa: A mysterious and alluring woman ...,"[0.0056173368357121944, -0.008345757611095905,..."
36,Baron Gustavo: A wealthy and arrogant nobleman...,"[-0.021879715844988823, -0.019812647253274918,..."
37,Francesca: A fiery and passionate young woman ...,"[-0.01607455685734749, -0.02415631152689457, -..."
38,Don Carlo: A charming and charismatic young ma...,"[-0.010879052802920341, -0.009095280431210995,..."
39,Duke Orsino: A pompous and self-important nobl...,"[-0.011212105862796307, -0.042800549417734146,..."
40,Lady Olivia: A wealthy and beautiful noblewoma...,"[-0.018390856683254242, -0.02478823810815811, ..."
41,Sir Toby Belch: A drunken and lecherous knight...,"[-0.0010516365291550756, -0.02924186922609806,..."
42,Malvolio: A pompous and self-righteous steward...,"[-0.015246011316776276, -0.03374519571661949, ..."
43,Viola: A plucky and resourceful young woman wh...,"[-0.013206351548433304, -0.042285721749067307,..."
44,Sir Andrew Aguecheek: A dim-witted and gullibl...,"[-0.024975545704364777, -0.027777161449193954,..."
45,Bianca: Lady Olivia's cunning and quick-witted...,"[-0.012050548568367958, -0.026455875486135483,..."
46,"Sebastian: Viola's twin brother, who is also s...","[-0.012644337490200996, -0.0394493043422699, 0..."
47,Feste: A jester and musician who works in Lady...,"[-0.009899717755615711, -0.023165076971054077,..."
48,Antonio: A sea captain who rescues Sebastian f...,"[-0.00845198705792427, -0.04057474061846733, 0..."
49,Abigail: A plucky and resourceful young woman ...,"[-0.029811017215251923, -0.02353024296462536, ..."
50,Thomas: A good-natured and affable young man w...,"[-0.016786592081189156, -0.011754455044865608,..."
51,Reverend Brown: The pious and stern minister o...,"[0.005873897112905979, -0.032237835228443146, ..."
52,Captain James: The charismatic and dashing cap...,"[-0.005605380516499281, -0.020872067660093307,..."
53,Mrs. Mercer: The matriarch of the wealthiest f...,"[-0.021774696186184883, -0.013641664758324623,..."
54,Mr. Mercer: The bumbling and absent-minded pat...,"[-0.016776707023382187, -0.015724152326583862,..."

In [8]:
# Using Code from 4.24 Case Study Workspace
# Load embeddings from file
#df = pd.read_csv("embeddings.csv", index_col=0)
#df["embeddings"] = df["embeddings"].apply(eval).apply(np.array)

In [9]:
# Using Code from 4.24 Case Study Workspace

from openai.embeddings_utils import get_embedding, distances_from_embeddings

def get_rows_sorted_by_relevance(question, df):
    """
    Function that takes in a question string and a dataframe containing
    rows of text and associated embeddings, and returns that dataframe
    sorted from least to most relevant for that question
    """
    
    # Get embeddings for the question text
    question_embeddings = get_embedding(question, engine=EMBEDDING_MODEL_NAME)
    
    # Make a copy of the dataframe and add a "distances" column containing
    # the cosine distances between each row's embeddings and the
    # embeddings of the question
    df_copy = df.copy()
    df_copy["distances"] = distances_from_embeddings(
        question_embeddings,
        df_copy["embeddings"].values,
        distance_metric="cosine"
    )
    
    # Sort the copied dataframe by the distances and return it
    # (shorter distance = more relevant so we sort in ascending order)
    df_copy.sort_values("distances", ascending=True, inplace=True)
    return df_copy

In [10]:
get_rows_sorted_by_relevance("retired soldier", df)

,text,embeddings,distances
3,"Tom: A man in his 50s, Tom is a retired soldie...","[0.017878901213407516, -0.017596535384655, 0.0...",0.166532
7,"John: A man in his 60s, John is a retired prof...","[0.019646571949124336, -0.013807781040668488, ...",0.199419
12,"Manuel: A middle-aged Hispanic man in his 50s,...","[-0.008526013232767582, -0.022947043180465698,...",0.222522
17,"Max: A white Australian man in his late 20s, M...","[0.0021642628125846386, -0.03667907789349556, ...",0.227160
1,"Jack: A middle-aged man in his 40s, Jack is a ...","[0.00714816665276885, -0.022021278738975525, 0...",0.233641
52,Captain James: The charismatic and dashing cap...,"[-0.005605380516499281, -0.020872067660093307,...",0.234605
13,"Will: A white man in his early 40s, Will is a ...","[-0.0026530236937105656, -0.046536002308130264...",0.238522
10,"Tyler: A white man in his mid-30s, Tyler is a ...","[0.013335198163986206, -0.048971496522426605, ...",0.241675
14,"Mia: A young Australian woman in her mid-20s, ...","[-0.013563292101025581, -0.022774379700422287,...",0.242706
29,James: A handsome and athletic personal traine...,"[-0.02195400930941105, -0.012563727796077728, ...",0.244160
33,"Jake: A laid-back and easygoing firefighter, J...","[-0.014207241125404835, -0.021265199407935143,...",0.245825
4,"Sarah: A woman in her mid-20s, Sarah is a free...","[-0.018298335373401642, -0.02350444905459881, ...",0.247085
5,"George: A man in his early 30s, George is a ch...","[-0.020879525691270828, -0.012621497735381126,...",0.247395
8,"Maria: A middle-aged Latina woman in her 40s, ...","[-0.006911840755492449, -0.013061589561402798,...",0.247461
15,Lucas: A middle-aged Australian man in his 40s...,"[0.004014276433736086, -0.0179184190928936, -0...",0.248140
54,Mr. Mercer: The bumbling and absent-minded pat...,"[-0.016776707023382187, -0.015724152326583862,...",0.248621
11,"Sonya: A white woman in her late 20s, Sonya is...","[0.006791851948946714, -0.03281968832015991, -...",0.249197
6,"Rachel: A woman in her late 20s, Rachel is a s...","[-0.0037319459952414036, -0.009705585427582264...",0.249515
51,Reverend Brown: The pious and stern minister o...,"[0.005873897112905979, -0.032237835228443146, ...",0.250474
48,Antonio: A sea captain who rescues Sebastian f...,"[-0.00845198705792427, -0.04057474061846733, 0...",0.252954
41,Sir Toby Belch: A drunken and lecherous knight...,"[-0.0010516365291550756, -0.02924186922609806,...",0.256652
9,Caleb: A young African American man in his ear...,"[0.006823256146162748, -0.029563192278146744, ...",0.257274
34,Prince Lorenzo: A charming and handsome prince...,"[-0.0037086326628923416, -0.015919039025902748...",0.257470
20,"Johnny: A young up-and-coming performer, Johnn...","[-0.03135303407907486, -0.024801846593618393, ...",0.260197
42,Malvolio: A pompous and self-righteous steward...,"[-0.015246011316776276, -0.03374519571661949, ...",0.261020
30,Sophia: A fun-loving and adventurous travel bl...,"[0.01387482974678278, -0.019231650978326797, -...",0.261652
32,"Chloe: A driven and ambitious attorney, Chloe ...","[-0.007095130626112223, -0.013222445733845234,...",0.263277
2,"Alice: A woman in her late 30s, Alice is a war...","[0.005913194734603167, -0.011871776543557644, ...",0.263698
28,Maya: A kind and compassionate nurse with a he...,"[-0.028294377028942108, -0.024649009108543396,...",0.263953
50,Thomas: A good-natured and affable young man w...,"[-0.016786592081189156, -0.011754455044865608,...",0.264690
49,Abigail: A plucky and resourceful young woman ...,"[-0.029811017215251923, -0.02353024296462536, ...",0.264709
44,Sir Andrew Aguecheek: A dim-witted and gullibl...,"[-0.024975545704364777, -0.027777161449193954,...",0.265964
53,Mrs. Mercer: The matriarch of the wealthiest f...,"[-0.021774696186184883, -0.013641664758324623,...",0.267006
36,Baron Gustavo: A wealthy and arrogant nobleman...,"[-0.021879715844988823, -0.019812647253274918,...",0.267646
37,Francesca: A fiery and passionate young woman ...,"[-0.01607455685734749, -0.02415631152689457, -...",0.269981
18,Ava: A middle-aged Australian woman in her 50s...,"[-0.00012268566933926195, -0.00761997047811746...",0.270051
40,Lady Olivia: A wealthy and beautiful noblewoma...,"[-0.018390856683254242, -0.02478823810815811, ...",0.270889
27,Marcus: A charming and successful entrepreneur...,"[-0.009401591494679451, -0.04195664823055267, ...",0.273769
43,Viola: A plucky and resourceful young woman wh...,"[-0.013206351548433304, -0.042285721749067307,...",0.273829
39,Duke Orsino: A pompous and self-important nobl...,"[-0.011212105862796307, -0.042800549417734146,...",0.274348
46,"Sebastian: Viola's twin brother, who is also s...","[-0.012644337490200996, -0.0394493043422699, 0...",0.275162
0,"Emily: A young woman in her early 20s, Emily i...","[-0.016379576176404953, -0.014448083005845547,...",0.275547
38,Don Carlo: A charming and charismatic young ma...,"[-0.010879052802920341, -0.009095280431210995,...",0.276199
19,Donna: A seasoned performer with a larger-than...,"[-0.027097031474113464, -0.018302153795957565,...",0.277007
31,"Noah: A quirky and creative graphic designer, ...","[-0.020587317645549774, -0.02017899602651596, ...",0.277021
35,Signora Rosa: A mysterious and alluring woman ...,"[0.0056173368357121944, -0.008345757611095905,...",0.278159
26,Olivia: A confident and charismatic marketing ...,"[-0.0073702577501535416, -0.016184642910957336...",0.278616
21,"Sable: A sultry and dramatic performer, Sable ...","[-0.029338078573346138, -0.018894359469413757,...",0.279094
22,"Dolly: A bubbly and vivacious performer, Dolly...","[-0.035839010030031204, -0.019233515486121178,...",0.283605
24,"Karma: A chameleon-like performer, Karma is kn...","[-0.005941613111644983, -0.018105927854776382,...",0.284265
47,Feste: A jester and musician who works in Lady...,"[-0.009899717755615711, -0.023165076971054077,...",0.288279
45,Bianca: Lady Olivia's cunning and quick-witted...,"[-0.012050548568367958, -0.026455875486135483,...",0.290297
25,"Crystal: A quirky and imaginative performer, C...","[-0.009453645907342434, -0.014112434349954128,...",0.294337
16,Tahlia: A young Indigenous Australian woman in...,"[-0.01594378985464573, -0.012738263234496117, ...",0.296871
23,"Vixen: A fierce and competitive performer, Vix...","[-0.036363694816827774, -0.025237884372472763,...",0.299439

In [11]:
# Using Code from 4.24 Case Study Workspace
# Create prompt, pay attention to max tokens

import tiktoken

def create_prompt(question, df, max_token_count):
    """
    Given a question and a dataframe containing rows of text and their
    embeddings, return a text prompt to send to a Completion model
    """
    # Create a tokenizer that is designed to align with our embeddings
    tokenizer = tiktoken.get_encoding("cl100k_base")
    
    # Count the number of tokens in the prompt template and question
    prompt_template = """
Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context: 

{}

---

Question: {}
Answer:"""
    
    current_token_count = len(tokenizer.encode(prompt_template)) + \
                            len(tokenizer.encode(question))
    
    context = []
    for text in get_rows_sorted_by_relevance(question, df)["text"].values:
        
        # Increase the counter based on the number of tokens in this row
        text_token_count = len(tokenizer.encode(text))
        current_token_count += text_token_count
        
        # Add the row of text to the list if we haven't exceeded the max
        if current_token_count <= max_token_count:
            context.append(text)
        else:
            break

    return prompt_template.format("\n\n###\n\n".join(context), question)

In [12]:
print(create_prompt("Who is currently in a relationship?", df, 200))

Answer the question based on the context below, and if the question
can't be answered based on the context, say "I don't know"

Context:

Jake: A laid-back and easygoing firefighter, Jake is the quintessential good guy. He's looking for someone who shares his values of honesty and integrity, and who is looking for a stable and committed relationship. He's a bit of a hopeless romantic, and is always looking for ways to sweep his partner off their feet., Reality Show, USA

###

Chloe: A driven and ambitious attorney, Chloe is always striving for success. She's looking for someone who can match her intellect and drive, and who is supportive of her career goals. She's a bit guarded when it comes to matters of the heart, but is ready to let her guard down for the right person., Reality Show, USA

---

Question: Who is currently in a relationship?
Answer:

In [13]:
# Using Code from 4.24 Case Study Workspace
# Answer a question

COMPLETION_MODEL_NAME = "gpt-3.5-turbo-instruct"

def answer_question(question, max_answer_tokens=150):
    response = openai.Completion.create(
        model=COMPLETION_MODEL_NAME,
        prompt=question,
        max_tokens=max_answer_tokens
    )
    return response["choices"][0]["text"].strip()

def answer_question_with_context(
    question, df, max_prompt_tokens=1800, max_answer_tokens=150
):
    """
    Given a question, a dataframe containing rows of text, and a maximum
    number of desired tokens in the prompt and response, return the
    answer to the question according to an OpenAI Completion model
    
    If the model produces an error, return an empty string
    """
    
    prompt = create_prompt(question, df, max_prompt_tokens)
    
    try:
        response = openai.Completion.create(
            model=COMPLETION_MODEL_NAME,
            prompt=prompt,
            max_tokens=max_answer_tokens
        )
        return response["choices"][0]["text"].strip()
    except Exception as e:
        print(e)
        return ""

## Custom Performance Demonstration

TODO: In the cells below, demonstrate the performance of your custom query using at least 2 questions. For each question, show the answer from a basic `Completion` model query as well as the answer from your custom query.

### Question 1

In [14]:
question1 = "Which characters are above 30?"

In [15]:
answer1 = answer_question(question1)
print(answer1)

It is not possible to answer this question without more context or information about which group of characters you are referring to. However, here are some examples of characters above 30 in various works of fiction:

1. Harry Potter - In the later books in the series, Harry and his friends are all above 30 years old.
2. Tony Stark (Iron Man) - In the Marvel Cinematic Universe, Tony Stark is over 30 years old during the events of the first Iron Man movie.
3. Elizabeth Bennet - In Jane Austen's Pride and Prejudice, Elizabeth is around 20 years old at the beginning of the novel, but by the end she is in her mid-30s.
4. Tyrion Lann

In [16]:
custom_answer1 = answer_question_with_context(question1, df)
print(custom_answer1)

John, Lucas, Ava, Jack, Maria, Ava, Tyler, Captain James, Manuel, Will, Duke Orsino, Sir Toby Belch, and Mrs. Mercer are all above 30.

### Question 2

In [17]:
question2 = "Who is currently in a relationship?"

In [18]:
answer2 = answer_question(question2)
print(answer2)

Without more context, it is impossible to determine who is currently in a relationship. The answer could be anyone in the world.

In [19]:
custom_answer2 = answer_question_with_context(question2, df)
print(custom_answer2)

George and Emily are currently in a relationship. Tom and Rachel are also in a relationship. Jack and Alice are married, which could also be considered a "relationship."

### Question 3

In [20]:
question3 = "Is Rachel in a relationship?"

In [21]:
answer3 = answer_question(question3)
print(answer3)

As an AI, Rachel does not have the capacity for romantic relationships. She is here to assist and answer questions.

In [22]:
custom_answer3 = answer_question_with_context(question3, df)
print(custom_answer3)

Yes, Rachel is in a relationship with Tom, as stated in the context.

### Question 4

In [26]:
question4 = "Which of the characters play an evil role?"

In [27]:
answer4 = answer_question(question4)
print(answer4)

The characters who play an evil role are usually the antagonists or villains of the story. Some examples include:

1. Lord Voldemort in the Harry Potter series
2. The Joker in Batman
3. Cersei Lannister in Game of Thrones
4. Hannibal Lecter in The Silence of the Lambs
5. Sauron in The Lord of the Rings
6. Maleficent in Sleeping Beauty
7. Darth Vader in Star Wars
8. Ursula in The Little Mermaid
9. Iago in Othello
10. Professor Moriarty in Sherlock Holmes.

In [28]:
custom_answer4 = answer_question_with_context(question4, df)
print(custom_answer4)

I don't know.